export const SWITCH_ACTIVE_TABBAR_KEY = 'SWITCH_ACTIVE_TABBAR_KEY'
export const SWITCH_ACTIVE_TABBAR_REQUEST = 'SWITCH_ACTIVE_TABBAR_REQUEST'
export const ADD_TOOLBAR_BUTTON_GENERATOR = 'ADD_TOOLBAR_BUTTON_GENERATOR'
