name: macOS Build
on:
  push:
    # tags:
    #   - 'v*'
jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Installing Node
        uses: actions/setup-node@v1
        with:
          version: 10

      - name: Install deps
        run: |
          yarn

      # - name: Build native deps
      #   run: scripts/build-native.js
      #
      # - name: Build typings
      #   run: yarn run build:typings

      - name: Webpack
        run: yarn run build

      # - name: Prepackage plugins
      #   run: scripts/prepackage-plugins.js

      - name: Build packages
        run: scripts/build-macos.js
        env:
          DEBUG: electron-builder,electron-builder:*
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

        #   CSC_LINK: ${{ secrets.CSC_LINK }}
        #   CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      - name: Package artifacts
        run: |
          mkdir artifact-dmg
          mv dist/*.dmg artifact-dmg/
          ls ./
          ls ./artifact-dmg

      - uses: actions/upload-artifact@master
        name: Upload DMG
        with:
          name: macOS.dmg
          path: artifact-dmg

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1.0.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     draft: false
      #     prerelease: false
      #
      # - name: Upload Release Asset
      #   id: upload-release-asset
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
      #     asset_path: ./artifact-dmg/lamp-0.0.1-macos.dmg
      #     asset_name: lamp-0.0.1-macos.dmg
      #     asset_content_type: application/octet-stream
