name: macOS Build
on: [push, pull_request]
jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Installing Node
      uses: actions/setup-node@v1
      with:
        version: 10

    - name: Install deps
      run: |
        yarn

    # - name: Build native deps
    #   run: scripts/build-native.js
    #
    # - name: Build typings
    #   run: yarn run build:typings

    - name: Webpack
      run: yarn run build

    # - name: Prepackage plugins
    #   run: scripts/prepackage-plugins.js

    - name: Build packages
      run: scripts/build-macos.js
      env:
        DEBUG: electron-builder,electron-builder:*
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #   CSC_LINK: ${{ secrets.CSC_LINK }}
      #   CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

    - name: Package artifacts
      run: |
        mkdir artifact-dmg
        mv dist/*.dmg artifact-dmg/

    - uses: actions/upload-artifact@master
      name: Upload DMG
      with:
        name: macOS.dmg
        path: artifact-dmg
